update: update VWO Smartcode to version 2.1
segmentio/analytics.js-integrations pull request #808
Opened 2024-12-17 09:03 UTC by zeeshan-vwo

What does this PR do?
This PR updates the VWO Smartcode in the project to the latest version (v2.1), replacing the outdated version to ensure compatibility and access to the latest features and improvements.

Are there breaking changes in this PR?
No, there are no breaking changes expected in this PR. The updated Smartcode is backward-compatible with existing functionality.

Any background context you want to provide?
The current project contains a very old version of the VWO Smartcode. Upgrading to version 2.1 ensures alignment with VWO’s latest updates and feature set.

Is there parity with the server-side/android/iOS integration components (if applicable)?
This PR is not directly related to server-side, Android, or iOS components.

Does this require a new integration setting? If so, please explain how the new setting works
No new integration settings are required for this update.

2025-01-15 22:33 UTC, seg-leonelsanches requested changes

2025-01-15 22:33 UTC, seg-leonelsanches commented on integrations/visual-website-optimizer/lib/index.js
> +      hide_element_style = 'opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;transition:none !important;',
This will reintroduce a problem resolved at #809, in which our customer has their webpage flickering because of `opacity: 0` and `filter: alpha(opacity=0)`.

2025-01-27 18:32 UTC, zeeshan-vwo commented
The VWO SmartCode v2.1 script when it gets executed auto-detects (detecting first-contentful-paint Ref: PerformancePaintTiming - Web APIs | MDN) if the page is already loaded then it prevents the page (body) from hiding from it.

Attached is the videos demonstrating the testing process. To replicate the scenario of asynchronously adding the Smartcode, the Smartcode is loaded 2 seconds after the page load using setTimeout within the script tag. Additionally, I conducted A/B tests to check for flickering across different variations. No flickering issues were detected during these tests. Please refer to the attached video for reference. 

Video - SmartCode Async Test Variation - 1,  Original Content, No white flicker detected
Video - SmartCode Async Test Variation - 2, A/B Test Variation, No white flicker detected

https://github.com/user-attachments/assets/4d0372e6-55b7-41e8-8031-60214a29f369

https://github.com/user-attachments/assets/71a780e5-dc7c-400f-a4c9-933f027b28a9

2025-01-27 18:37 UTC, seg-leonelsanches commented on integrations/visual-website-optimizer/lib/index.js
> +      hide_element_style = 'opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;transition:none !important;',
@zeeshan-vwo Can you please update your PR with the following comment, before line 55? 

```
The VWO SmartCode v2.1 script when it gets executed auto-detects (detecting first-contentful-paint Ref: [PerformancePaintTiming - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming)) if the page is already loaded then it prevents the page (body) from hiding from it.
```

2025-02-05 22:54 UTC, maryamsharif approved these changes

2025-02-11 15:55 UTC, merged